// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package sqlc

import (
	"database/sql"
	"time"
)

type Author struct {
	ID        int64
	Name      string
	Bio       sql.NullString
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Book struct {
	ID        int64
	Title     string
	AuthorID  int64
	CreatedAt time.Time
	UpdatedAt time.Time
}
